targets:
  $default:
    builders:
      flutter_secure_dotenv_generator|flutter_secure_dotenv:
        enabled: true

builders:
  flutter_secure_dotenv:
    target: ":flutter_secure_dotenv_generator"
    import: "package:flutter_secure_dotenv_generator/flutter_secure_dotenv_generator.dart"
    builder_factories: ["flutterSecureDotEnvAnnotation"]
    build_extensions: { ".dart": [".flutter_secure_dotenv.g.part"] }
    auto_apply: dependents
    build_to: cache
    applies_builders: ["source_gen|combining_builder"]